import re

translations = {
    "Австралийский английский": "Australian English",
    "Австрийский немецкий": "Austrian German",
    "Азербайджанский": "Azerbaijani",
    "Албанский": "Albanian",
    "Американский английский": "American English",
    "Английский (Великобритания)": "British English",
    "Англиш (Anglish)": "Anglish",
    "Андалузский": "Andalusian",
    "Арабский": "Arabic",
    "Аргентинский испанский": "Argentine Spanish",
    "Армянский": "Armenian",
    "Ассамский": "Assamese",
    "Астурийский": "Asturian",
    "Африкаанс": "Afrikaans",
    "Баварский": "Bavarian",
    "Баскский": "Basque",
    "Башкирский": "Bashkir",
    "Белорусский": "Belarusian",
    "Бенгальский": "Bengali",
    "Болгарский": "Bulgarian",
    "Боснийский": "Bosnian",
    "Брабантский": "Brabantian",
    "Бразильский португальский": "Brazilian Portuguese",
    "Бретонский": "Breton",
    "Валлийский": "Welsh",
    "Венгерский": "Hungarian",
    "Венесуэльский испанский": "Venezuelan Spanish",
    "Вьетнамский": "Vietnamese",
    "Гавайский": "Hawaiian",
    "Галисийский": "Galician",
    "Греческий": "Greek",
    "Грузинский": "Georgian",
    "Датский": "Danish",
    "Зулу": "Zulu",
    "Иврит": "Hebrew",
    "Игбо": "Igbo",
    "Идо": "Ido",
    "Индонезийский": "Indonesian",
    "Ирландский": "Irish",
    "Исландский": "Icelandic",
    "Испанский": "Spanish",
    "Итальянский": "Italian",
    "Йоруба": "Yoruba",
    "Кабильский": "Kabyle",
    "Казахский": "Kazakh",
    "Канадский английский": "Canadian English",
    "Канадский французский": "Canadian French",
    "Каннада": "Kannada",
    "Каталанский": "Catalan",
    "Квенья": "Quenya",
    "Кёльнский": "Colognian",
    "Киргизский": "Kyrgyz",
    "Китайский (Гонконг)": "Chinese (Hong Kong)",
    "Китайский (Тайвань)": "Chinese (Taiwan)",
    "Китайский (Упрощенный)": "Chinese (Simplified)",
    "Клингонский": "Klingon",
    "Корейский": "Korean",
    "Корнский": "Cornish",
    "Крымскотатарский": "Crimean Tatar",
    "Латинский": "Latin",
    "Латвийский": "Latvian",
    "Лимбургский": "Limburgish",
    "Литовский": "Lithuanian",
    "Ложбан": "Lojban",
    "Люксембургский": "Luxembourgish",
    "Македонский": "Macedonian",
    "Малайский": "Malay",
    "Малаялам": "Malayalam",
    "Мальтийский": "Maltese",
    "Маори": "Maori",
    "Маратхи": "Marathi",
    "Межславянский": "Interslavic",
    "Мексиканский испанский": "Mexican Spanish",
    "Монгольский": "Mongolian",
    "Мэнский": "Manx",
    "Немецкий": "German",
    "Нидерландский": "Dutch",
    "Нижнесаксонский": "Low Saxon",
    "Новозеландский английский": "New Zealand English",
    "Норвежский (Букмол)": "Norwegian (Bokmål)",
    "Норвежский (Нюнорск)": "Norwegian (Nynorsk)",
    "Окситанский": "Occitan",
    "Пенджабский": "Punjabi",
    "Перевёрнутый английский (ɥsᴉꞁᵷuƎ)": "Upside Down English",
    "Персидский": "Persian",
    "Пиратский английский": "Pirate English",
    "Польский": "Polish",
    "Португальский": "Portuguese",
    "Пушту": "Pashto",
    "Румынский": "Romanian",
    "Русский": "Russian",
    "Северносаамский": "Northern Sami",
    "Сербский": "Serbian",
    "Силезский": "Silesian",
    "Сингальский": "Sinhala",
    "Словацкий": "Slovak",
    "Словенский": "Slovenian",
    "Сомалийский": "Somali",
    "Суахили": "Swahili",
    "Таджикский": "Tajik",
    "Тайский": "Thai",
    "Тамильский": "Tamil",
    "Татарский": "Tatar",
    "Телугу": "Telugu",
    "Токипона": "Toki Pona",
    "Турецкий": "Turkish",
    "Туркменский": "Turkmen",
    "Узбекский": "Uzbek",
    "Украинский": "Ukrainian",
    "Уругвайский испанский": "Uruguayan Spanish",
    "Фарерский": "Faroese",
    "Филиппинский": "Filipino",
    "Финский": "Finnish",
    "Французский": "French",
    "Фризский": "Frisian",
    "Хинди": "Hindi",
    "Хорватский": "Croatian",
    "Черногорский": "Montenegrin",
    "Чешский": "Czech",
    "Чилийский испанский": "Chilean Spanish",
    "Чувашский": "Chuvash",
    "Шведский": "Swedish",
    "Швейцарский немецкий": "Swiss German",
    "Шекспировский английский": "Shakespearean English",
    "Шотландский (Германский)": "Scots",
    "Шотландский (Гэльский)": "Scottish Gaelic",
    "Эквадорский испанский": "Ecuadorian Spanish",
    "Эсперанто": "Esperanto",
    "Эстонский": "Estonian",
    "Южноафриканский английский": "South African English",
    "Язык лолкотов (LOLCAT)": "LOLCAT",
    "Японский": "Japanese"
}

with open("C:/Users/79129/Desktop/XDAetherium-main/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/utils/LanguageDatabase.java", "r", encoding="utf-8") as f:
    content = f.read()

for ru, en in translations.items():
    content = content.replace(f'"{ru}"', f'"{ru} ({en})"')

with open("C:/Users/79129/Desktop/XDAetherium-main/app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/utils/LanguageDatabase.java", "w", encoding="utf-8") as f:
    f.write(content)
