package net.kdt.pojavlaunch.utils;

import java.util.ArrayList;
import java.util.List;

public class LanguageDatabase {
    public static final List<MCLanguage> LANGUAGES = new ArrayList<>();

    static {
        LANGUAGES.add(new MCLanguage("Не менять (По умолчанию)", "default"));
        LANGUAGES.add(new MCLanguage("English (Australia)", "en_au"));
        LANGUAGES.add(new MCLanguage("Deitsch (Österreich)", "de_at"));
        LANGUAGES.add(new MCLanguage("Azərbaycanca (Azərbaycan)", "az_az"));
        LANGUAGES.add(new MCLanguage("Shqip (Shqipëri)", "sq_al"));
        LANGUAGES.add(new MCLanguage("English (US)", "en_us"));
        LANGUAGES.add(new MCLanguage("English (United Kingdom)", "en_gb"));
        LANGUAGES.add(new MCLanguage("Anglish", "en_pt"));
        LANGUAGES.add(new MCLanguage("Andalûh (Andalucía)", "es_an"));
        LANGUAGES.add(new MCLanguage("العربية (العالم العربي)", "ar_sa"));
        LANGUAGES.add(new MCLanguage("Español (Argentina)", "es_ar"));
        LANGUAGES.add(new MCLanguage("Հայերեն (Հայաստան)", "hy_am"));
        LANGUAGES.add(new MCLanguage("অসমীয়া (ভাৰত)", "as_in"));
        LANGUAGES.add(new MCLanguage("Asturianu (Asturies)", "ast_es"));
        LANGUAGES.add(new MCLanguage("Afrikaans (Suid-Afrika)", "af_za"));
        LANGUAGES.add(new MCLanguage("Boarisch (Bayern)", "bar"));
        LANGUAGES.add(new MCLanguage("Euskara (Euskal Herria)", "eu_es"));
        LANGUAGES.add(new MCLanguage("Башҡортса (Башҡортостан, Рәсәй)", "ba_ru"));
        LANGUAGES.add(new MCLanguage("Беларуская (Беларусь)", "be_by"));
        LANGUAGES.add(new MCLanguage("বাংলা (বাংলাদেশ)", "bn_bd"));
        LANGUAGES.add(new MCLanguage("Български (България)", "bg_bg"));
        LANGUAGES.add(new MCLanguage("Bosanski (Bosna i Hercegovina)", "bs_ba"));
        LANGUAGES.add(new MCLanguage("Braobans (Braobant)", "brb"));
        LANGUAGES.add(new MCLanguage("Português (Brasil)", "pt_br"));
        LANGUAGES.add(new MCLanguage("Brezhoneg (Breizh)", "br_fr"));
        LANGUAGES.add(new MCLanguage("Cymraeg (Cymru)", "cy_gb"));
        LANGUAGES.add(new MCLanguage("Magyar (Magyarország)", "hu_hu"));
        LANGUAGES.add(new MCLanguage("Español (Venezuela)", "es_ve"));
        LANGUAGES.add(new MCLanguage("Tiếng Việt (Việt Nam)", "vi_vn"));
        LANGUAGES.add(new MCLanguage("ʻŌlelo Hawaiʻi (Hawaiʻi)", "haw_us"));
        LANGUAGES.add(new MCLanguage("Galego (Galicia / Galiza)", "gl_es"));
        LANGUAGES.add(new MCLanguage("Ελληνικά (Ελλάδα)", "el_gr"));
        LANGUAGES.add(new MCLanguage("ქართული (საქართველო)", "ka_ge"));
        LANGUAGES.add(new MCLanguage("Dansk (Danmark)", "da_dk"));
        LANGUAGES.add(new MCLanguage("isiZulu (Ningizimu Afrika)", "zu_za"));
        LANGUAGES.add(new MCLanguage("עברית (ישראל)", "he_il"));
        LANGUAGES.add(new MCLanguage("Igbo (Naigeria)", "ig_ng"));
        LANGUAGES.add(new MCLanguage("Ido (Idia)", "io_en"));
        LANGUAGES.add(new MCLanguage("Bahasa Indonesia (Indonesia)", "id_id"));
        LANGUAGES.add(new MCLanguage("Gaeilge (Éire)", "ga_ie"));
        LANGUAGES.add(new MCLanguage("Íslenska (Ísland)", "is_is"));
        LANGUAGES.add(new MCLanguage("Español (España)", "es_es"));
        LANGUAGES.add(new MCLanguage("Italiano (Italia)", "it_it"));
        LANGUAGES.add(new MCLanguage("Yorùbá (Nàìjíríà)", "yo_ng"));
        LANGUAGES.add(new MCLanguage("Taqbaylit (Lezzayer)", "kab_dz"));
        LANGUAGES.add(new MCLanguage("Қазақша (Қазақстан)", "kk_kz"));
        LANGUAGES.add(new MCLanguage("English (Canada)", "en_ca"));
        LANGUAGES.add(new MCLanguage("Français (Canada)", "fr_ca"));
        LANGUAGES.add(new MCLanguage("ಕನ್ನಡ (ಭಾರತ)", "kn_in"));
        LANGUAGES.add(new MCLanguage("Català (Catalunya)", "ca_es"));
        LANGUAGES.add(new MCLanguage("Quenya (Arda)", "qya_aa"));
        LANGUAGES.add(new MCLanguage("Kölsch/Ripoarisch (Rhingland)", "ksh"));
        LANGUAGES.add(new MCLanguage("Кыргызча (Кыргызстан)", "ky_kg"));
        LANGUAGES.add(new MCLanguage("繁體中文 (香港特別行政區)", "zh_hk"));
        LANGUAGES.add(new MCLanguage("繁體中文 (台灣)", "zh_tw"));
        LANGUAGES.add(new MCLanguage("简体中文 (中国大陆)", "zh_cn"));
        LANGUAGES.add(new MCLanguage("tlhIngan Hol (tlhIngan wo')", "tlh_aa"));
        LANGUAGES.add(new MCLanguage("한국어 (대한민국)", "ko_kr"));
        LANGUAGES.add(new MCLanguage("Kernewek (Kernow)", "kw_gb"));
        LANGUAGES.add(new MCLanguage("Qırımtatarca (Ukraina)", "crh_tr"));
        LANGUAGES.add(new MCLanguage("Latina (Latium)", "la_la"));
        LANGUAGES.add(new MCLanguage("Latviešu (Latvija)", "lv_lv"));
        LANGUAGES.add(new MCLanguage("Limburgs (Limburg)", "li_li"));
        LANGUAGES.add(new MCLanguage("Lietuvių (Lietuva)", "lt_lt"));
        LANGUAGES.add(new MCLanguage("la .lojban. (la jbogu'e)", "jbo_en"));
        LANGUAGES.add(new MCLanguage("Lëtzebuergesch (Lëtzebuerg)", "lb_lu"));
        LANGUAGES.add(new MCLanguage("Македонски (Северна Македонија)", "mk_mk"));
        LANGUAGES.add(new MCLanguage("Bahasa Melayu (Malaysia)", "ms_my"));
        LANGUAGES.add(new MCLanguage("മലയാളം (ഇന്ത്യ)", "ml_in"));
        LANGUAGES.add(new MCLanguage("Malti (Malta)", "mt_mt"));
        LANGUAGES.add(new MCLanguage("Māori (Aotearoa)", "mi_nz"));
        LANGUAGES.add(new MCLanguage("मराठी (भारत)", "mr_in"));
        LANGUAGES.add(new MCLanguage("Medžuslovjansky (Slovjanščina)", "isv"));
        LANGUAGES.add(new MCLanguage("Español (México)", "es_mx"));
        LANGUAGES.add(new MCLanguage("Монгол (Монгол Улс)", "mn_mn"));
        LANGUAGES.add(new MCLanguage("Gaelg (Ellan Vannin)", "gv_im"));
        LANGUAGES.add(new MCLanguage("Deutsch (Deutschland)", "de_de"));
        LANGUAGES.add(new MCLanguage("Nederlands (Nederland)", "nl_nl"));
        LANGUAGES.add(new MCLanguage("Plattdüütsch (Düütschland)", "nds_de"));
        LANGUAGES.add(new MCLanguage("English (New Zealand)", "en_nz"));
        LANGUAGES.add(new MCLanguage("Norsk bokmål (Norge)", "no_no"));
        LANGUAGES.add(new MCLanguage("Norsk nynorsk (Noreg)", "nn_no"));
        LANGUAGES.add(new MCLanguage("Occitan (Occitània)", "oc_fr"));
        LANGUAGES.add(new MCLanguage("ਪੰਜਾਬੀ (ਭਾਰਤ)", "pa_in"));
        LANGUAGES.add(new MCLanguage("ɥsᴉꞁᵷuƎ (uʍoᗡ ǝpᴉsd∩)", "en_ud"));
        LANGUAGES.add(new MCLanguage("فارسی (ايران)", "fa_ir"));
        LANGUAGES.add(new MCLanguage("Pirate Speak", "en_ws"));
        LANGUAGES.add(new MCLanguage("Polski (Polska)", "pl_pl"));
        LANGUAGES.add(new MCLanguage("Português (Portugal)", "pt_pt"));
        LANGUAGES.add(new MCLanguage("پښتو (افغانستان)", "ps_af"));
        LANGUAGES.add(new MCLanguage("Română (România)", "ro_ro"));
        LANGUAGES.add(new MCLanguage("Русский (Россия)", "ru_ru"));
        LANGUAGES.add(new MCLanguage("Davvisámegiella (Sápmi)", "se_no"));
        LANGUAGES.add(new MCLanguage("Српски (Србија)", "sr_sp"));
        LANGUAGES.add(new MCLanguage("Ślōnski (Gōrny Ślōnsk)", "szl"));
        LANGUAGES.add(new MCLanguage("සිංහල (ශ්‍රී ලංකාව)", "si_lk"));
        LANGUAGES.add(new MCLanguage("Slovenčina (Slovensko)", "sk_sk"));
        LANGUAGES.add(new MCLanguage("Slovenščina (Slovenija)", "sl_si"));
        LANGUAGES.add(new MCLanguage("Soomaali (Soomaaliya)", "so_so"));
        LANGUAGES.add(new MCLanguage("Kiswahili (Kenya)", "sw_ke"));
        LANGUAGES.add(new MCLanguage("Тоҷикӣ (Тоҷикистон)", "tg_tj"));
        LANGUAGES.add(new MCLanguage("ไทย (ประเทศไทย)", "th_th"));
        LANGUAGES.add(new MCLanguage("தமிழ் (இந்தியா)", "ta_in"));
        LANGUAGES.add(new MCLanguage("Татарча (Татарстан, Рәсәй)", "tt_ru"));
        LANGUAGES.add(new MCLanguage("తెలుగు (భారత దేశం)", "te_in"));
        LANGUAGES.add(new MCLanguage("toki pona (kulupu pona)", "tok"));
        LANGUAGES.add(new MCLanguage("Türkçe (Türkiye)", "tr_tr"));
        LANGUAGES.add(new MCLanguage("Türkmen (Türkmenistan)", "tk_tm"));
        LANGUAGES.add(new MCLanguage("Oʻzbek (Oʻzbekiston)", "uz_uz"));
        LANGUAGES.add(new MCLanguage("Українська (Україна)", "uk_ua"));
        LANGUAGES.add(new MCLanguage("Español (Uruguay)", "es_uy"));
        LANGUAGES.add(new MCLanguage("Føroyskt (Føroyar)", "fo_fo"));
        LANGUAGES.add(new MCLanguage("Filipino (Pilipinas)", "fil_ph"));
        LANGUAGES.add(new MCLanguage("Suomi (Suomi)", "fi_fi"));
        LANGUAGES.add(new MCLanguage("Français (France)", "fr_fr"));
        LANGUAGES.add(new MCLanguage("Frysk (Fryslân)", "fy_nl"));
        LANGUAGES.add(new MCLanguage("हिंदी (भारत)", "hi_in"));
        LANGUAGES.add(new MCLanguage("Hrvatski (Hrvatska)", "hr_hr"));
        LANGUAGES.add(new MCLanguage("Crnogorski (Crna Gora)", "cnr_me"));
        LANGUAGES.add(new MCLanguage("Čeština (Česko)", "cs_cz"));
        LANGUAGES.add(new MCLanguage("Español (Chile)", "es_cl"));
        LANGUAGES.add(new MCLanguage("Чӑваш (Ҫӗршыв)", "cv_ru"));
        LANGUAGES.add(new MCLanguage("Svenska (Sverige)", "sv_se"));
        LANGUAGES.add(new MCLanguage("Schwiizerdütsch (Schwiiz)", "de_ch"));
        LANGUAGES.add(new MCLanguage("Shakespearean English", "en_7s"));
        LANGUAGES.add(new MCLanguage("Scots (Scotland)", "sco_gb"));
        LANGUAGES.add(new MCLanguage("Gàidhlig (Alba)", "gd_gb"));
        LANGUAGES.add(new MCLanguage("Español (Ecuador)", "es_ec"));
        LANGUAGES.add(new MCLanguage("Esperanto (Esperantujo)", "eo_uy"));
        LANGUAGES.add(new MCLanguage("Eesti keel (Eesti)", "et_ee"));
        LANGUAGES.add(new MCLanguage("English (South Africa)", "en_za"));
        LANGUAGES.add(new MCLanguage("LOLCAT (Kingdom of Cats)", "lol_us"));
        LANGUAGES.add(new MCLanguage("日本語 (日本)", "ja_jp"));
    }
}
